### ISSUE TITLE
请问我们这个程序,支持ipv6吗

### ISSUE THREAD

**Issue by zhaojun1217** [Kokomi7QAQ/wirebare-android#10]
我有在上下行的看到IPV4的提示,想问一下是否支持ipv6,从代码上来看,只有ipv4header,address相关, 如果暂不支持v6我们有计划加这个吗?

**Comment by Kokomi7QAQ** [comment]
> 我有在上下行的看到IPV4的提示,想问一下是否支持ipv6,从代码上来看,只有ipv4header,address相关, 如果暂不支持v6我们有计划加这个吗?

现在是不支持ipv6的，现在还在了解ipv6的相关知识，以后有计划加上的

**Comment by zhaojun1217** [comment]
我最近刚开始接触v6,会做一些尝试,期待后续更新

**Comment by Kokomi7QAQ** [comment]
> 我最近刚开始接触v6,会做一些尝试,期待后续更新

现已支持 IPv6

**Comment by Kokomi7QAQ** [comment]
详见项目的自述文件

**Comment by Kokomi7QAQ** [comment]
@zhaojun1217
