### ISSUE TITLE
请问高版本获取HTTPS数据需要Root权限，这个是具体是版本和原因

### ISSUE THREAD

**Issue by altmangood** [Kokomi7QAQ/wirebare-android#11]
是否是因为系统证书问题

**Comment by Kokomi7QAQ** [comment]
> 是否是因为系统证书问题

是因为android7.0以后，android不再信任用户安装的证书，因此7.0以后需要获取root权限并把根证书安装到系统证书目录下才能抓https

目前我没有提供这个根证书，如果你需要的话我提供一下

**Comment by te3** [comment]
> > 是否是因为系统证书问题
> 
> 是因为android7.0以后，android不再信任用户安装的证书，因此7.0以后需要获取root权限并把根证书安装到系统证书目录下才能抓https
> 
> 目前我没有提供这个根证书，如果你需要的话我提供一下

麻烦提供一下证书吧，谢谢！
另外？可以自己创建这个证书吗？
keytool -genkeypair -alias wirebare -keyalg RSA -keysize 2048 -validity 365 -sigalg SHA384withRSA -keystore wirebare.jks -storetype PKCS12
这样创建出来的证书貌似用不了？

**Comment by Kokomi7QAQ** [comment]
> > > 是否是因为系统证书问题
> > 
> > 
> > 是因为android7.0以后，android不再信任用户安装的证书，因此7.0以后需要获取root权限并把根证书安装到系统证书目录下才能抓https
> > 目前我没有提供这个根证书，如果你需要的话我提供一下
> 
> 麻烦提供一下证书吧，谢谢！ 另外？可以自己创建这个证书吗？ keytool -genkeypair -alias wirebare -keyalg RSA -keysize 2048 -validity 365 -sigalg SHA384withRSA -keystore wirebare.jks -storetype PKCS12 这样创建出来的证书貌似用不了？

已经上传了需要的证书文件和使用说明，在主分支根目录的certificate目录下

**Comment by Kokomi7QAQ** [comment]
@te3 @altmangood

**Comment by te3** [comment]
请教一下，只能将证书装在root系统下吗？HttpCanary可以将证书装在用户信任区域实现解包，跟wirebare有什么本质区别吗？

**Comment by Kokomi7QAQ** [comment]
> 请教一下，只能将证书装在root系统下吗？HttpCanary可以将证书装在用户信任区域实现解包，跟wirebare有什么本质区别吗？

@te3 不一定，低版本安卓（7.0以下）系统是信任用户安装的凭证的，但之后（7.0及以上）就不再信任了，如果要进行https解密，那就只能装到系统的证书目录下才可以，这一点跟你提到的httpcanary应该是一致的

**Comment by Kokomi7QAQ** [comment]
> 请教一下，只能将证书装在root系统下吗？HttpCanary可以将证书装在用户信任区域实现解包，跟wirebare有什么本质区别吗？

@te3 有什么问题可以微信聊一聊？如果方便的话

**Comment by Kokomi7QAQ** [comment]
wx号：f939826156
